"""Day-41: Programmatically-generated held-out StableHLO corpus.

Phase E critique: the StableHLO evaluation uses `stablehlo_spec_30`,
which was *authored* alongside the grammar → circularity concern.

This script builds a NEW, larger corpus (`stablehlo_held_out_50`) from a
small parametric DSL. Programs are generated by sweeping:

  - op family  {elementwise-binary, elementwise-unary, transpose,
                reshape, broadcast, compare, dot_general, select}
  - dtypes     {f16, f32, f64, i8, i32, i64}
  - shapes     {1D fixed, 2D fixed, 3D fixed} with varied dims
  - multi-op   compositions (2-3 ops in sequence)

Each candidate is verify-checked via iree-compile; only compilable
programs are kept. The natural-language description is
*templated from the op signature* (no access to the grammar design
during NL construction), which reduces author-influence bias.

Output: `eval/benchmarks/stablehlo_held_out_50/examples/*.json`
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO = "/Users/plawanrath/Documents/GitHub-public/slm-to-mlir-constrained-emitter"
os.chdir(REPO); sys.path.insert(0, REPO)

from scripts.env.verify_stablehlo import verify_stablehlo

OUT_DIR = Path("eval/benchmarks/stablehlo_held_out_50/examples")

EW_BIN = ["add", "subtract", "multiply", "divide", "maximum", "minimum", "power", "remainder"]
EW_UN = ["abs", "exponential", "log", "sqrt", "negate", "cosine", "sine", "tanh", "floor", "ceil"]
DTYPES = ["f16", "f32", "f64", "i8", "i32", "i64"]

SHAPES_1D = [8, 16, 32, 64, 128]
SHAPES_2D = [(4, 4), (8, 16), (16, 32), (32, 64)]
SHAPES_3D = [(2, 4, 4), (2, 8, 8), (4, 4, 16)]


@dataclass
class Candidate:
    id: str
    nl: str
    mlir: str
    notes: str = ""


def _shape_str(dims) -> str:
    if isinstance(dims, int):
        return f"tensor<{dims}x{{dtype}}>"
    return f"tensor<{'x'.join(str(d) for d in dims)}x{{dtype}}>"


def _ew_bin_candidates() -> list[Candidate]:
    out = []
    i = 0
    for op in EW_BIN:
        # not all ops accept int dtypes; use a safe subset
        safe_dtypes = ["f32", "f16", "f64"] if op in ("divide", "power", "exponential") else DTYPES
        for dtype in safe_dtypes[:4]:
            for shape in [16, (8, 8), (4, 4, 4)]:
                i += 1
                t = _shape_str(shape).format(dtype=dtype)
                shape_desc = f"{shape}" if isinstance(shape, int) else "x".join(str(s) for s in shape)
                nl = (f"Write a function that applies stablehlo.{op} elementwise "
                      f"to two {dtype} tensors of shape {shape_desc}.")
                mlir = (
                    "module {\n"
                    f"  func.func @f(%a: {t}, %b: {t}) -> {t} {{\n"
                    f"    %0 = stablehlo.{op} %a, %b : {t}\n"
                    f"    return %0 : {t}\n"
                    "  }\n"
                    "}"
                )
                out.append(Candidate(id=f"ew_bin_{i:02d}_{op}_{dtype}_{shape_desc}",
                                     nl=nl, mlir=mlir, notes=f"{op} {dtype} {shape_desc}"))
    return out


def _ew_un_candidates() -> list[Candidate]:
    out = []
    i = 0
    for op in EW_UN:
        for dtype in ["f32", "f16", "f64"]:
            for shape in [32, (4, 8)]:
                i += 1
                t = _shape_str(shape).format(dtype=dtype)
                shape_desc = f"{shape}" if isinstance(shape, int) else "x".join(str(s) for s in shape)
                nl = (f"Write a function that applies stablehlo.{op} "
                      f"elementwise to a {dtype} tensor of shape {shape_desc}.")
                mlir = (
                    "module {\n"
                    f"  func.func @f(%a: {t}) -> {t} {{\n"
                    f"    %0 = stablehlo.{op} %a : {t}\n"
                    f"    return %0 : {t}\n"
                    "  }\n"
                    "}"
                )
                out.append(Candidate(id=f"ew_un_{i:02d}_{op}_{dtype}_{shape_desc}",
                                     nl=nl, mlir=mlir, notes=f"{op} {dtype} {shape_desc}"))
    return out


def _reshape_candidates() -> list[Candidate]:
    pairs = [
        ((16,), (4, 4)),
        ((16,), (2, 8)),
        ((8, 8), (64,)),
        ((4, 16), (2, 2, 16)),
        ((2, 3, 4), (6, 4)),
        ((12,), (3, 4)),
    ]
    out = []
    for i, (src, dst) in enumerate(pairs, start=1):
        for dtype in ["f32", "i32"]:
            t_src = f"tensor<{'x'.join(str(d) for d in src)}x{dtype}>"
            t_dst = f"tensor<{'x'.join(str(d) for d in dst)}x{dtype}>"
            sd = "x".join(str(d) for d in src); dd = "x".join(str(d) for d in dst)
            nl = (f"Write a function that reshapes a {dtype} tensor of shape "
                  f"{sd} to shape {dd} using stablehlo.reshape.")
            mlir = (
                "module {\n"
                f"  func.func @f(%a: {t_src}) -> {t_dst} {{\n"
                f"    %0 = stablehlo.reshape %a : ({t_src}) -> {t_dst}\n"
                f"    return %0 : {t_dst}\n"
                "  }\n"
                "}"
            )
            out.append(Candidate(id=f"reshape_{i:02d}_{dtype}_{sd}_to_{dd}",
                                 nl=nl, mlir=mlir, notes=f"reshape {sd}→{dd}"))
    return out


def _transpose_candidates() -> list[Candidate]:
    cases = [
        ((8, 16), [1, 0]),
        ((4, 8), [1, 0]),
        ((2, 4, 8), [0, 2, 1]),
        ((2, 3, 4), [2, 1, 0]),
        ((3, 5, 7), [1, 2, 0]),
    ]
    out = []
    for i, (src, perm) in enumerate(cases, start=1):
        for dtype in ["f32", "f16"]:
            dst = tuple(src[p] for p in perm)
            t_src = f"tensor<{'x'.join(str(d) for d in src)}x{dtype}>"
            t_dst = f"tensor<{'x'.join(str(d) for d in dst)}x{dtype}>"
            sd = "x".join(str(d) for d in src)
            perm_s = ", ".join(str(p) for p in perm)
            nl = (f"Write a function that transposes a {dtype} tensor of shape "
                  f"{sd} with permutation [{perm_s}] using stablehlo.transpose.")
            mlir = (
                "module {\n"
                f"  func.func @f(%a: {t_src}) -> {t_dst} {{\n"
                f"    %0 = stablehlo.transpose %a, dims = [{perm_s}] : ({t_src}) -> {t_dst}\n"
                f"    return %0 : {t_dst}\n"
                "  }\n"
                "}"
            )
            out.append(Candidate(id=f"transpose_{i:02d}_{dtype}_{sd}_p{''.join(str(p) for p in perm)}",
                                 nl=nl, mlir=mlir, notes=f"transpose {sd} perm={perm}"))
    return out


def _multi_op_candidates() -> list[Candidate]:
    out = []
    cases = [
        {
            "id": "add_then_mul",
            "nl": "Write a function that adds two f32 1-D tensors of 16 elements, then multiplies by a third.",
            "mlir": (
                "module {\n"
                "  func.func @f(%a: tensor<16xf32>, %b: tensor<16xf32>, %c: tensor<16xf32>) -> tensor<16xf32> {\n"
                "    %0 = stablehlo.add %a, %b : tensor<16xf32>\n"
                "    %1 = stablehlo.multiply %0, %c : tensor<16xf32>\n"
                "    return %1 : tensor<16xf32>\n"
                "  }\n"
                "}"
            ),
        },
        {
            "id": "abs_then_sqrt",
            "nl": "Write a function that takes the abs then the sqrt of a f32 tensor of shape 8x8.",
            "mlir": (
                "module {\n"
                "  func.func @f(%a: tensor<8x8xf32>) -> tensor<8x8xf32> {\n"
                "    %0 = stablehlo.abs %a : tensor<8x8xf32>\n"
                "    %1 = stablehlo.sqrt %0 : tensor<8x8xf32>\n"
                "    return %1 : tensor<8x8xf32>\n"
                "  }\n"
                "}"
            ),
        },
        {
            "id": "reshape_then_transpose",
            "nl": "Write a function that reshapes a f32 tensor of shape 16 to 4x4, then transposes it.",
            "mlir": (
                "module {\n"
                "  func.func @f(%a: tensor<16xf32>) -> tensor<4x4xf32> {\n"
                "    %0 = stablehlo.reshape %a : (tensor<16xf32>) -> tensor<4x4xf32>\n"
                "    %1 = stablehlo.transpose %0, dims = [1, 0] : (tensor<4x4xf32>) -> tensor<4x4xf32>\n"
                "    return %1 : tensor<4x4xf32>\n"
                "  }\n"
                "}"
            ),
        },
        {
            "id": "sub_then_exp",
            "nl": "Write a function that subtracts one f32 tensor from another of shape 2x8 then applies exp.",
            "mlir": (
                "module {\n"
                "  func.func @f(%a: tensor<2x8xf32>, %b: tensor<2x8xf32>) -> tensor<2x8xf32> {\n"
                "    %0 = stablehlo.subtract %a, %b : tensor<2x8xf32>\n"
                "    %1 = stablehlo.exponential %0 : tensor<2x8xf32>\n"
                "    return %1 : tensor<2x8xf32>\n"
                "  }\n"
                "}"
            ),
        },
        {
            "id": "div_then_log",
            "nl": "Write a function that divides one f32 tensor by another of shape 4x4 then applies log.",
            "mlir": (
                "module {\n"
                "  func.func @f(%a: tensor<4x4xf32>, %b: tensor<4x4xf32>) -> tensor<4x4xf32> {\n"
                "    %0 = stablehlo.divide %a, %b : tensor<4x4xf32>\n"
                "    %1 = stablehlo.log %0 : tensor<4x4xf32>\n"
                "    return %1 : tensor<4x4xf32>\n"
                "  }\n"
                "}"
            ),
        },
    ]
    for c in cases:
        out.append(Candidate(id=c["id"], nl=c["nl"], mlir=c["mlir"], notes="multi-op"))
    return out


def _verify(mlir: str) -> bool:
    res = verify_stablehlo(mlir)
    return res["returncode"] == 0


def build(target_n: int = 50) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    candidates = []
    candidates += _ew_bin_candidates()
    candidates += _ew_un_candidates()
    candidates += _reshape_candidates()
    candidates += _transpose_candidates()
    candidates += _multi_op_candidates()
    print(f"[day41] {len(candidates)} raw candidates", file=sys.stderr)

    kept: list[Candidate] = []
    for c in candidates:
        if _verify(c.mlir):
            kept.append(c)
        else:
            print(f"  reject {c.id}", file=sys.stderr)
        if len(kept) >= target_n:
            break
    print(f"[day41] kept {len(kept)}/{len(candidates)} verify-clean", file=sys.stderr)

    # Write to disk with monotonic numeric prefix
    for existing in OUT_DIR.glob("*.json"):
        existing.unlink()
    for i, c in enumerate(kept, start=1):
        path = OUT_DIR / f"{i:02d}_{c.id}.json"
        path.write_text(json.dumps({
            "id": f"{i:02d}_{c.id}",
            "difficulty": "programmatic",
            "nl": c.nl,
            "mlir": c.mlir,
            "notes": c.notes,
            "dialect": "stablehlo+func",
            "source": "day41_programmatic_sweep",
        }, indent=2))
    print(f"[day41] wrote {len(kept)} examples to {OUT_DIR}", file=sys.stderr)


if __name__ == "__main__":
    build(target_n=int(os.environ.get("DAY41_N", "50")))
