"""Phase F F11: emit Croissant metadata (core + RAI fields) for each
benchmark, for venue-required machine-readable dataset metadata.

Writes `croissant.json` at each
`eval/benchmarks/<name>/croissant.json`. Each file follows MLCommons
Croissant 1.0 schema with Responsible-AI extensions.
"""
from __future__ import annotations
import json, os, sys
from pathlib import Path

REPO = str(Path(__file__).resolve().parents[1])
os.chdir(REPO); sys.path.insert(0, REPO)


def _context():
    return {
        "@language": "en",
        "@vocab": "https://schema.org/",
        "sc": "https://schema.org/",
        "cr": "http://mlcommons.org/croissant/",
        "rai": "http://mlcommons.org/croissant/RAI/",
        "dct": "http://purl.org/dc/terms/",
        "data": {
            "@id": "cr:data",
            "@type": "@json"
        },
        "dataType": {"@id": "cr:dataType", "@type": "@vocab"},
        "examples": {"@id": "cr:examples", "@type": "@json"},
    }


def _emit(name: str, description: str, n: int, sampling_note: str,
          out_dir: Path, author_curated: bool, has_synthetic_data: bool) -> None:
    out = {
        "@context": _context(),
        "@type": "sc:Dataset",
        "name": name,
        "description": description,
        "conformsTo": "http://mlcommons.org/croissant/1.0",
        "license": "https://spdx.org/licenses/Apache-2.0.html",
        "version": "1.0.0",
        "datePublished": "2026-04-21",
        "citeAs": ("Cross-Dialect Generalization Without Retraining: "
                   "Benchmarks and Evaluation of Schema-Derived "
                   "Constrained Decoding for MLIR. Anonymous "
                   "submission, currently under review."),
        "url": "<populated-at-camera-ready>",
        "distribution": [
            {
                "@type": "cr:FileObject",
                "@id": f"{name}-archive",
                "name": f"{name}.zip",
                "contentUrl": "<populated-at-camera-ready>",
                "encodingFormat": "application/zip",
                "sha256": "<populated-at-camera-ready>"
            }
        ],
        "recordSet": [
            {
                "@type": "cr:RecordSet",
                "@id": "records",
                "name": "records",
                "description": "One MLIR prompt/reference pair per record.",
                "field": [
                    {"@type": "cr:Field", "@id": "records/id", "name": "id",
                     "dataType": "sc:Text",
                     "description": "Unique record identifier."},
                    {"@type": "cr:Field", "@id": "records/nl", "name": "nl",
                     "dataType": "sc:Text",
                     "description": "Natural-language description."},
                    {"@type": "cr:Field", "@id": "records/mlir", "name": "mlir",
                     "dataType": "sc:Text",
                     "description": "Reference MLIR that verifies under mlir-opt/iree-compile."},
                    {"@type": "cr:Field", "@id": "records/dialect", "name": "dialect",
                     "dataType": "sc:Text",
                     "description": "MLIR dialect of the reference program."},
                    {"@type": "cr:Field", "@id": "records/difficulty", "name": "difficulty",
                     "dataType": "sc:Text",
                     "description": "Author-assigned difficulty or 'programmatic'."}
                ]
            }
        ],
        "rai:dataCollection": (
            "Hand-authored by the submitting author against the target MLIR dialect's ODS."
            if author_curated
            else "Generated by parametric sweep over the target dialect's opset and "
                 "filtered by verifier acceptance; no sampling from crawled corpora."
        ),
        "rai:dataBiases": [
            (
                "Author-curated: prompts reflect the submitting author's mental model of "
                "the target dialect; may under-represent op combinations not present in the spec examples."
                if author_curated
                else "Parametric-sweep: coverage is uniform over the enumerated op × dtype × shape space; "
                     "biases toward simple single-op programs after iree-compile filtering."
            ),
            "No human-subject data; no PII; no demographic bias dimensions apply."
        ],
        "rai:dataLimitations": [
            "Verify-valid pass-rate measures structural validity under mlir-opt/iree-compile, "
            "not functional correctness. Programs that pass the gate may still compute the wrong function.",
            "English natural-language descriptions only.",
            "Small n (30-200 prompts per dataset) yields CI half-widths of ~3-10pp at p=0.5."
        ],
        "rai:annotationsPerExample": 0,
        "rai:annotationDemographics": "N/A — no human annotators.",
        "rai:personalSensitiveInformation": "None.",
        "rai:dataUseCases": [
            "Evaluating NL→MLIR generation systems (constrained or unconstrained) under a verifier-based pass-rate metric.",
            "Out of scope: evaluating functional correctness without an additional lowering + execution harness; training or fine-tuning production code-generation models without a separate held-out corpus."
        ],
        "rai:dataSocialImpact": (
            "These benchmarks are intended to evaluate compiler-IR generation systems against MLIR/StableHLO verifiers. "
            "They contain no human-subject, demographic, or PII content, and pose no direct risk to individuals or groups. "
            "The principal social risk is methodological: over-reliance on verifier-pass-rate as a proxy for functional "
            "correctness could lead to overstated claims about model capability. Downstream users should pair these "
            "benchmarks with execution/property-based testing before drawing conclusions about deployment readiness."
        ),
        "rai:hasSyntheticData": has_synthetic_data,
        "extra": {
            "size": n,
            "sampling": sampling_note
        }
    }
    out_path = out_dir / "croissant.json"
    out_path.write_text(json.dumps(out, indent=2))
    print(f"[f11] wrote {out_path}", file=sys.stderr)


def main():
    specs = [
        ("MLIR-Spec-150", 150,
         "Hand-authored NL→MLIR pairs for arith+func+memref dialects; 38/44/18% easy/medium/hard mix; all reference MLIR verify-clean under mlir-opt --verify-diagnostics.",
         "Author-curated (single author), covering the 12 named ops in scope.",
         Path("eval/benchmarks/mlir_spec_150"), True, False),
        ("Linalg-Spec-30", 30,
         "Hand-authored NL→MLIR pairs for linalg named ops under memref semantics (matmul, matvec, fill, copy, transpose, broadcast, add, sub, mul, div, exp, abs).",
         "Author-curated (single author), 12 linalg named ops.",
         Path("eval/benchmarks/linalg_spec_30"), True, False),
        ("StableHLO-Spec-30", 30,
         "Hand-authored NL→MLIR pairs for StableHLO dialect covering 10 op families.",
         "Author-curated (single author), 10 op families.",
         Path("eval/benchmarks/stablehlo_spec_30"), True, False),
        ("StableHLO-Held-Out-200", 200,
         "Programmatically generated StableHLO programs via parametric sweep over 7 op families × 6 dtypes × 3 shape ranks × multi-op compositions (585 candidates); kept only those that iree-compile accepts.",
         "Parametric sweep, verifier-filtered.",
         Path("eval/benchmarks/stablehlo_held_out_200"), False, True),
        ("StableHLO-OutOfGrammar-25", 25,
         "StableHLO programs using ops NOT in our 10-op grammar scope (reduce, convolution, pad, dynamic_slice, iota, clamp, select, compare, concatenate, slice, rsqrt, sign, tanh, sort, power, reverse, round_nearest_even, is_finite, shift_left, xor, popcnt, gather, dynamic_update_slice). Used to document graceful degradation of the constraint stack.",
         "Hand-authored out-of-grammar; verifier-filtered (all 25 iree-compile-clean).",
         Path("eval/benchmarks/stablehlo_outofgrammar_25"), True, False),
    ]
    for name, n, desc, sampling, out_dir, author_curated, has_synthetic in specs:
        if out_dir.exists():
            _emit(name, desc, n, sampling, out_dir, author_curated, has_synthetic)


if __name__ == "__main__":
    main()
